### ISSUE TITLE
Won't connect to the load

### ISSUE THREAD

**Issue by Grandchuck** [misdoro/Electronic_load_px100#1]
[python atorch display.pdf](https://github.com/misdoro/Electronic_load_px100/files/5180135/python.atorch.display.pdf)

Any suggestion as to how to troubleshoot?

**Comment by misdoro** [comment]
:thinking: I haven't yet tested on windows, it is in my todo list.

**Comment by Grandchuck** [comment]
Thanks Mikhail.  It looks like a nice effort.  Thanks for sharing.

Sent from Mail for Windows 10

**Comment by misdoro** [comment]
Hi @Grandchuck , I've finally tested my code on Windows and after a few minor tweaks it works fine.

Are you using the px100 electronic load on windows? I see Atorch 24 in your file path, this code is not (yet?) compatible with other devices/binary protocols.

**Comment by Grandchuck** [comment]
Hi Mikhail.  

I am using the Atorch 24.  Another user reported on EEVBLOG that your software works with his Atorch 24.  

I downloaded your latest version but it does not work with my Atorch.

Thanks so much for your efforts.  I realize you cannot support all situations.  Thanks for sharing!

Chuck

Sent from Mail for Windows 10

**Comment by misdoro** [comment]
Thank you for those details @Grandchuck. There are probably multiple versions of that load.

Looking at https://auto-scripting.com/2020/05/03/atorch-dl24-hack-1/ the binary protocol is completely different from the one used by PX-100. Is your load connecting via bluetooth or by usb cable?

**Comment by Grandchuck** [comment]
USB cable.

Sent from Mail for Windows 10

**Comment by misdoro** [comment]
@Grandchuck just in case, can you please test the latest version from https://github.com/misdoro/Electronic_load_px100/archive/master.zip ?

**Comment by Grandchuck** [comment]
Hello Mikhail,

Thanks for the alert.  I tried it but no luck:  I attached a screen shot.  The cell discharge graphic window appears and looks nice!



Sent from Mail for Windows 10
