### ISSUE TITLE
Protocol

### ISSUE THREAD

**Issue by Kabron287** [misdoro/Electronic_load_px100#2]
`The control frame looks like:
  0xB1 0xB2 CMD D1 D2 0xB3 0xB4`

Are you sure?

My experiments show:
0xB1 0xB2 CMD D1 D2 0xB6

**Comment by misdoro** [comment]
Oups, good catch, you are absolutely right!

The python code itself was correct, only the protocol description had this error. I was writing it too late at night :facepalm:
