### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by garag45** [misdoro/Electronic_load_px100#4]
Здравствуйте, Михаил. Продавец Electronic_load_px100 дал ссылку на ваше ПО. Хочу попробовать его (ПО), но не могу запустить, так как командная строка в винде, а тем более в питон - густые сумерки. Вроде походил, почитал, попробовал, но никак. Win7х64   python-3.8.6-amd64. Программа [ddt4all](https://github.com/cedricp/ddt4all/), тоже на питоне, работает. 
Просьба, если не затруднит, посоветуйте что и как сделать.

**Comment by garag45** [comment]
Здравствуйте, Михаил. С командной строкой разобрался.  Нет запроса от PC к PX100. Смотрел осциллографом на ТТЛ. Нет сигнала. Пробовал Win7, Win10, Pithon 3.6, 3.8, 3.9 в разных сочетаниях.  Да, китайский софт работает и сигнал отсслеживается. В чем может быть проблема?

Hello Mikhail. Dealt with the command line. No request from PC to PX100. I looked at TTL with an oscilloscope. No signal. Tried Win7, Win10, Pithon 3.6, 3.8, 3.9 in various combinations. Yes, the Chinese software works and the signal is tracked. What could be the problem?

**Comment by misdoro** [comment]
Добрый вечер!

Скажите, а что при этом выводится в консоль python ?

По идее, программа при старте ищет все последовательные порты в системе, и по порядку пытается через каждый отправить команду на чтение из нагрузки. Если получен ответ, используется этот порт, если нет, ищется дальше по порядку.

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


 Здравствуйте, 
Сделал скрины. На 7 и 10. 
Благодарю за отклик.
=========
С уважением,  Василий.             Сб 07.11.20          v45@bk.ru
===============================
Добрый вечер!
Скажите, а что при этом выводится в консоль python ?

**Comment by misdoro** [comment]
github похоже не прикрепляет картинки из вложений к письмам

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


https://www.dropbox.com/sh/vufn8yfnstisqze/AABmgyzEMBSMQpz6-irHfZ0ua?dl=0 

***https://www.dropbox.com/sh/vufn8yfnstisqze/AABmgyzEMBSMQpz6-irHfZ0ua?dl=0***
 
  
=========
С уважением,  Василий.             Сб 07.11.20          v45@bk.ru
===============================
github похоже не прикрепляет картинки из вложений к письмам

**Comment by misdoro** [comment]
Спасибо, попробуйте пожалуйста последнюю версию из https://github.com/misdoro/Electronic_load_px100/archive/master.zip , я добавил обработку ошибки открытия устройства.

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Добавил скрины туда же.
Запросов так же нет.
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
Спасибо, попробуйте пожалуйста последнюю версию из https://github.com/misdoro/Electronic_load_px100/archive/master.zip , я добавил обработку ошибки открытия устройства.

**Comment by misdoro** [comment]
Спасибо, прогресс виден :)
Добавил еще задание скорости порта перед подключением, проверьте пожалуйста, по тому же адресу https://github.com/misdoro/Electronic_load_px100/archive/master.zip

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Это вам спасибо.
  отправил 7.3
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
Спасибо, прогресс виден :)
Добавил еще задание скорости порта перед подключением, проверьте пожалуйста, по тому же адресу https://github.com/misdoro/Electronic_load_px100/archive/master.zip

**Comment by misdoro** [comment]
Странно.
У вас нагрузка какой модели-версии?
Сможете записать лог обмена между китайской программой и нагрузкой?

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Плата 2.8  ПО 2.45  китайская прога работает, запрос и далее обмен виден на осциллограмме. 
Для записи лога нужны аппаратные средства? По крайней мере постараюсь.
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
Странно.
У вас нагрузка какой модели-версии?
Сможете записать лог обмена между китайской программой и нагрузкой?

**Comment by misdoro** [comment]
У меня плата 2.70, может они протокол слегка поменяли.

Записать можно программно, я https://www.eltima.com/products/serial-port-monitor/ пользовался когда реверсил протокол своей.

**Comment by misdoro** [comment]
Попробуйте еще версию из https://github.com/misdoro/Electronic_load_px100/archive/debug.zip
Добавил больше отладочной информации в консоль

**Comment by garag45** [comment]
Добавил видео с осцилла.

=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
У меня плата 2.70, может они протокол слегка поменяли.
Записать можно программно, я https://www.eltima.com/products/serial-port-monitor/пользовался когда реверсил протокол своей.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[  {  "@context": "http://schema.org",  "@type": "EmailMessage",  "potentialAction": {  "@type": "ViewAction",  "target": "https://github.com/misdoro/Electronic_load_px100/issues/4#issuecomment-723505936",  "url": "https://github.com/misdoro/Electronic_load_px100/issues/4#issuecomment-723505936",  "name": "View Issue"  },  "description": "View this Issue on GitHub",  "publisher": {  "@type": "Organization",  "name": "GitHub",  "url": "https://github.com"  }  }  ]

**Comment by garag45** [comment]
Попробую снять лог, но завтра. Упадок сил, извините.
Результат отправлю.
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
У меня плата 2.70, может они протокол слегка поменяли.
Записать можно программно, я https://www.eltima.com/products/serial-port-monitor/пользовался когда реверсил протокол своей.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[  {  "@context": "http://schema.org",  "@type": "EmailMessage",  "potentialAction": {  "@type": "ViewAction",  "target": "https://github.com/misdoro/Electronic_load_px100/issues/4#issuecomment-723505936",  "url": "https://github.com/misdoro/Electronic_load_px100/issues/4#issuecomment-723505936",  "name": "View Issue"  },  "description": "View this Issue on GitHub",  "publisher": {  "@type": "Organization",  "name": "GitHub",  "url": "https://github.com"  }  }  ]

**Comment by misdoro** [comment]
Спасибо, судя по осциллограмме, протокол тот же, скорость обмена 9600 бод.

Немного поправил инициализацию, попробуйте пожалуйста завтра отладочную версию из https://github.com/misdoro/Electronic_load_px100/archive/debug.zip , скорее всего заработает.

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Здравствуйте. Попробовал последнюю отладочную. Отправил вам на 7-ке и на 10-ке с адаптером на ftdi ориг.
SPMonitor установил. Если подскажете последовательность получения лога, будет быстрее. Если нет, буду разбираться.
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
Спасибо, судя по осциллограмме, протокол тот же, скорость обмена 9600 бод.
Немного поправил инициализацию, попробуйте пожалуйста завтра отладочную версию из https://github.com/misdoro/Electronic_load_px100/archive/debug.zip , скорее всего заработает.

**Comment by misdoro** [comment]
Добавил еще немного отладочных сообщений в  https://github.com/misdoro/Electronic_load_px100/archive/debug.zip , попробуйте пожалуйста еще раз

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


С радостью.
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
Добавил еще немного отладочных сообщений в https://github.com/misdoro/Electronic_load_px100/archive/debug.zip , попробуйте пожалуйста еще раз

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Отправил скрины..
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
Добавил еще немного отладочных сообщений в https://github.com/misdoro/Electronic_load_px100/archive/debug.zip , попробуйте пожалуйста еще раз

**Comment by misdoro** [comment]
Спасибо, странно, выглядит как ошибка записи в порт. А можете попробовать Python 3.8, ошибка та же?

**Comment by garag45** [comment]
Собрал стенд, может поможет чем то. (видео там же)
Поставлю 3.8 и проверю.

=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
Спасибо, странно, выглядит как ошибка записи в порт. А можете попробовать Python 3.8, ошибка та же?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[  {  "@context": "http://schema.org",  "@type": "EmailMessage",  "potentialAction": {  "@type": "ViewAction",  "target": "https://github.com/misdoro/Electronic_load_px100/issues/4#issuecomment-723593622",  "url": "https://github.com/misdoro/Electronic_load_px100/issues/4#issuecomment-723593622",  "name": "View Issue"  },  "description": "View this Issue on GitHub",  "publisher": {  "@type": "Organization",  "name": "GitHub",  "url": "https://github.com"  }  }  ]

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Удаляю питон и вижу интерфейс NI Python Interface (скрин), Может конфликт?
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
Спасибо, странно, выглядит как ошибка записи в порт. А можете попробовать Python 3.8, ошибка та же?

**Comment by misdoro** [comment]
точно, скорее всего не та версия visa подключается по умолчанию. Добавил принудительный выбор версии pyvisa-py, можете еще раз попробовать https://github.com/misdoro/Electronic_load_px100/archive/debug.zip ?

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Сейчас 3.8 доустановлю на 7, и попробую.
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
точно, скорее всего не та версия visa подключается по умолчанию. Добавил принудительный выбор версии pyvisa-py, можете еще раз попробовать https://github.com/misdoro/Electronic_load_px100/archive/debug.zip ?

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Скрины установки и пробы.
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
точно, скорее всего не та версия visa подключается по умолчанию. Добавил принудительный выбор версии pyvisa-py, можете еще раз попробовать https://github.com/misdoro/Electronic_load_px100/archive/debug.zip ?

**Comment by misdoro** [comment]
На десятке так же не работает ?

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


По 10 отправил. На ней те же библиотеки стоят.
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
На десятке так же не работает ?

**Comment by misdoro** [comment]
Еще поправил версию debug, попробуйте пожалуйста на десятке

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


На 10 побежало.
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
Еще поправил версию debug, попробуйте пожалуйста на десятке

**Comment by misdoro** [comment]
А на семёрке последний вариант debug ?

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Побежала!
  
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
А на семёрке последний вариант debug ?

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Михаил, программа очень понравилась. Особенно режим CC-CV Очень! В общем снимаю шляпу. 
Я не совсем понял как должны работать функции под символами, на главной вкладке. По-моему они не фиксируются. Это мелочи.
  СПАСИБО.
=========
С уважением,  Василий.             Вс 08.11.20          v45@bk.ru
===============================
А на семёрке последний вариант debug ?

**Comment by misdoro** [comment]
Спасибо за отзыв :)
Иконки над графиком пока ничего особого не делают, можно только сохранить скриншот картинки.

Можно вас попросить проверить версию из ветки debug2: https://github.com/misdoro/Electronic_load_px100/archive/debug2.zip

Если она тоже работает, обновлю основную ветку программы.
Спасибо.

**Comment by garag45** [comment]
Re: [misdoro/Electronic_load_px100] Installing (#4)


Работает и на 7 и на 10.
Всегда буду рад помочь, обращайтесь без церемоний.
Подскажите, где хранятся настройки? Если сбросить или удалить.
Спасибо.
=========
С уважением,  Василий.             Пн 09.11.20          v45@bk.ru
===============================
Спасибо за отзыв :)
Иконки над графиком пока ничего особого не делают, можно только сохранить скриншот картинки.
Можно вас попросить проверить версию из ветки debug2: https://github.com/misdoro/Electronic_load_px100/archive/debug2.zip
Если она тоже работает, обновлю основную ветку программы.
Спасибо.

**Comment by misdoro** [comment]
Отлично!

Настройки в реестре, `HKEY_CURRENT_USER\Software\github.com/misdoro\Battery tester`
