### ISSUE TITLE
'This app can't run on your PC'

### ISSUE THREAD

**Issue by debros** [misdoro/Electronic_load_px100#8]
Hi, unfortunately despite many attempts I keep getting the message 'This app can't run on your PC'. Windows 10 Home 32bit 20H2, 19042.844. Maybe you have an idea how to solve this, thank you! Greetings / Rafael

**Comment by misdoro** [comment]
Hi!
Good spot.
I think for the moment only 64-bit windows versions are supported.

**Comment by debros** [comment]
Oh, what a pity. I saw a short presentation on YouTube, the program looks really great. Thank you very much for the information.

**Comment by misdoro** [comment]
@debros can you please try this installer https://github.com/misdoro/Electronic_load_px100/releases/download/v0.1.2/Battery-Tester-PX100-x86.exe ? It should be compatible with 32-bit windows.

BTW, do you have a link to that video? I'm pretty curious to see it :)

**Comment by debros** [comment]
Not only should it be, but it is compatible! :-) It works perfectly, I am very impressed. I don't know how to thank you :-) Here is the moment when your program appears (connected with the new version of DL24), in the short words of the film's author: "the program is fucking good." I'm happy to agree with him, albeit in more cultural terms ;-)
https://youtu.be/JpnySkpVHdc?t=353

**Comment by misdoro** [comment]
Great, thank you for the kind feedback @debros, I'm closing this issue then.
